### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sdaros** [sdaros/ber01#1]
Here we can organize our TODOs.

- [x] Wie binden wir externe Tiles ein?
- [x] Amphiteatre fläche erweitern
- [x] [sdaros] URL zu OwlyBase
- [x] Welcome message! - DONE
- [x] Kreis wegbekommen ==> ggf. bug
- [x] Popup Example aufbauen.
- [x] 13 Stühle am Tisch 
- [x] generell mehr Get2Gether Working areas (2-4 Personen) 
- [x] Silent Area nahe der Lounge 
- [x] Layer Inhalte checken
- [x] Eingangstür einbauen (Entry Point) 
- [x] Welt vergrößern 
- [x] Keithstraße einbauen
- [x] Entry / Leave testen 
- [x] GitHub für Collaboration mit weiteren Dep. vorbereiten 
- [x] [sdaros] Esspressobar next world (map)
- [x] zweite Kaffemaschine :-) 
- [ ] URL zum Harmony?
- [ ] "Wegbeschreibungen" auf dem Boden 
- [ ] Schriftart angleichen
- [ ] Wichmannstraße einbauen 
- [ ] Tiergarten vorbereiten 
- [ ] Common Area aufbauen (Gym, Espressobar, Kindergarten, ... ) 
- [ ] Issue Board in Welt einbetten als "Ideenportal"

**Comment by patman1987** [comment]
[ ] Welt vergrößern 
[ ] Keithstraße einbauen 
[ ] Wichmannstraße einbauen 
[ ] Tiergarten vorbereiten 
[ ] Common Area aufbauen (Gym, Espressobar, Kindergarten, ... ) 
[ ] Entry / Leave testen 
[ ] GitHub für Collaboration mit weiteren Dep. vorbereiten 
[ ] Issue Board in Welt einbetten als "Ideenportal"
